apiVersion: apps/v1
kind: Deployment
metadata:
  name: acwebapi-deployment
spec:
  selector:
    matchLabels:
      app: acwebapi-pod
  template:
    metadata:
      labels:
        app: acwebapi-pod
    spec:
      containers:
      - name: myapacwebapi-container
        image: devonacr.azurecr.io/acwebapi:weather
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
